name: "pr"

on:
  push:
    branches:
      - "**"
      - "!main"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ‚¨£ ESlint
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run linting checks
        run: |
          pnpm run lint:check
  format:
    name: üéÄ Prettier
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier checks
        run: |
          pnpm run format:check
  typecheck:
    name:  ¶ TypeScript
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run typescript checks
        run: |
          pnpm run typecheck
  knip:
    name: ‚úÇÔ∏è Knip
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run knip
        run: |
          pnpm run knip
  e2e:
    name: üé≠ E2E
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    env:
      SESSION_SECRET: "s3cret"
      APP_DATABASE_URL: "sqlite.db"
      SENDGRID_API_KEY: "NA"
      ENCRYPTION_KEY: "ad1915128c35d60577830804d7aab68a6e706d39d46a6218fb9edf113a410da7"

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: |
          pnpm run build

      - name: Install playwright browsers
        run: |
          pnpm exec playwright install --with-deps chromium

      - name: üé≠ Playwright tests
        run: pnpm exec playwright test

      - name: üìä Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
