name: "pr"

on:
  push:
    branches:
      - "**"
      - "!main"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ‚¨£ ESlint
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Run linting checks
        run: |
          npm run lint:check
  format:
    name: üéÄ Prettier
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Run prettier checks
        run: |
          npm run format:check
  typecheck:
    name:  ¶ TypeScript
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Run typescript checks
        run: |
          npm run typecheck
  knip:
    name: ‚úÇÔ∏è Knip
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Run knip
        run: |
          npm run typecheck
          npm run knip
  e2e:
    name: üé≠ E2E
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    env:
      SESSION_SECRET: "s3cret"
      APP_DATABASE_URL: "sqlite.db"
      SENDGRID_API_KEY: "NA"
      ENCRYPTION_KEY: "ad1915128c35d60577830804d7aab68a6e706d39d46a6218fb9edf113a410da7"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Run build
        run: |
          npm run build

      - name: Install playwright browsers
        run: |
          npx playwright install --with-deps chromium

      - name: üé≠ Playwright tests
        run: npx playwright test

      - name: üìä Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
